# Generated by Django 5.1.2 on 2024-10-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrequest',
            name='severity',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='', max_length=30),
        ),
    ]
