# Generated by Django 5.1.2 on 2024-10-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0002_medicalrequest_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrequest',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
