# Generated by Django 5.1.2 on 2024-10-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0003_medicalrequest_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrequest',
            name='duration',
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='duration_amount',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default=('days', 'Days'), max_length=30),
        ),
    ]
