# Generated by Django 5.1.2 on 2024-10-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0006_alter_medicalrequest_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrequest',
            name='duration_type',
            field=models.TextField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default=('days', 'Days'), max_length=30),
        ),
    ]
