# Generated by Django 5.1.2 on 2024-10-15 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0008_medicalrequest_created_at_medicalrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
