# Generated by Django 5.1.2 on 2024-10-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0009_alter_medicalrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrequest',
            name='escalating_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='original_cost',
            field=models.IntegerField(default=0),
        ),
    ]
