# Generated by Django 5.1.2 on 2024-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0012_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
