# Generated by Django 5.1.2 on 2024-11-03 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0014_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrequest',
            name='inmate_id',
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='inmate',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthwatch_ai_app.user'),
        ),
    ]
