# Generated by Django 5.1.2 on 2024-11-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0015_remove_medicalrequest_inmate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrequest',
            name='issue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
