# Generated by Django 5.1.2 on 2024-11-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0016_medicalrequest_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrequest',
            old_name='description',
            new_name='inmate_description',
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='provider_summary',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
