# Generated by Django 5.1.2 on 2024-11-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0017_rename_description_medicalrequest_inmate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_results', 'Awaiting Results'), ('follow_up_required', 'Follow Up Required'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
