# Generated by Django 5.1.2 on 2024-11-22 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0018_medicalrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('unit_number', models.CharField(default='', max_length=100)),
                ('assignment', models.CharField(default='', max_length=100)),
                ('requested_outcome', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=30)),
                ('submission_count', models.IntegerField(default=1)),
                ('last_submission_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('escalated', models.BooleanField(default=False)),
                ('inmate', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthwatch_ai_app.user')),
            ],
        ),
    ]
