# Generated by Django 5.1.2 on 2024-11-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0019_grievancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inmate_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
