# Generated by Django 5.1.2 on 2024-11-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0020_user_inmate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inmate_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
