# Generated by Django 5.1.2 on 2024-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwatch_ai_app', '0021_alter_user_inmate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
